export enum ERROR_CODES {
  SERVER_ERROR = "SERVER_ERROR",

  // NOT FOUND
  ROOM_NOT_FOUND = "ROOM_NOT_FOUND",
  PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
  FACT_NOT_FOUND = "FACT_NOT_FOUND",

  // ROOM ERRORS
  GAME_ALREADY_STARTED = "GAME_ALREADY_STARTED",
  NOT_ENOUGH_PLAYERS = "NOT_ENOUGH_PLAYERS",
  ROOM_AT_MAX_CAPACITY = "ROOM_AT_MAX_CAPACITY",
  VOTING_PHASE_NOT_ACTIVE = "VOTING_PHASE_NOT_ACTIVE",
  WRONG_FACT_VOTING = "WRONG_FACT_VOTING",

  // PLAYER ERRORS
  PLAYER_NAME_ALREADY_EXISTS = "PLAYER_NAME_ALREADY_EXISTS",
  PLAYER_NAME_TOO_LONG = "PLAYER_NAME_TOO_LONG",
  PLAYER_NAME_TOO_SHORT = "PLAYER_NAME_TOO_SHORT",
  AVATAR_ALREADY_TAKEN = "AVATAR_ALREADY_TAKEN",
  PLAYER_ALREADY_SUBMITTED_FACT = "PLAYER_ALREADY_SUBMITTED_FACT",

  // FACT ERRORS
  DUPLICATE_FACT = "DUPLICATE_FACT",
  FACT_TEXT_TOO_LONG = "FACT_TEXT_TOO_LONG",
  FACT_TEXT_TOO_SHORT = "FACT_TEXT_TOO_SHORT",

  // VOTING
  VOTING_DATA_NOT_FOUND = "VOTING_DATA_NOT_FOUND",
  ALREADY_VOTED_FOR_FACT_IN_CURRENT_ROUND = "ALREADY_VOTED_FOR_FACT_IN_CURRENT_ROUND",

  // RESULTS
  GAME_RESULTS_NOT_FOUND = "GAME_RESULTS_NOT_FOUND",
}
