export enum ERROR_CODE {
  // join errors
  MAX_ROOM_CAPACITY_JOIN_ERROR = "MAX_ROOM_CAPACITY_JOIN_ERROR",
  PLAYER_NAME_ALREADY_EXISTS_JOIN_ERROR = "PLAYER_NAME_ALREADY_EXISTS_JOIN_ERROR",
  GAME_ALREADY_STARTED_JOIN_ERROR = "GAME_ALREADY_STARTED_JOIN_ERROR",
  ROOM_NOT_FOUND_JOIN_ERROR = "ROOM_NOT_FOUND_JOIN_ERROR",

  // create or reenter room errors
  ROOM_NOT_FOUND_BY_HOST_ID_REENTER_ERROR = "ROOM_NOT_FOUND_BY_HOST_ID_REENTER_ERROR",
}
